
development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: hindavi_employee_development
  pool: 5
  username: root
  password: root

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: hindavi_employee_test
  pool: 5
  username: root
  password: root

production:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: hindavi_employee_production
  pool: 5
  username: root
  password: root
